title: Arnab Bera
logo: /assets/img/logo.jpg
description: 
  <p align="center">
  <a href="https://github.com/arnabberawork/portfolio/blob/master/docs/Arnab%20Bera_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/arnabbera-tech/">LinkedIn</a> |
  <a href="https://github.com/arnabberawork">GitHub</a>
  <br>   
  AI Engineer | ML | Data Science | Python | API Integration
  <br>
  </p>
theme: jekyll-theme-minimal
